name: "Docker Build"
 
on:
  push:
    # branches: master
    tags:
      - "v*.*"
 
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Calculate Docker tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["photonixapp/photonix:latest","photonixapp/photonix:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["photonixapp/photonix:latest"]'
          fi
          echo $TAGS
          echo '::set-output name=tags::'$TAGS
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.prd
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ fromJson(steps.docker_tags.outputs.tags) }}
          cache-from: type=registry,ref=photonixapp/photonix:latest
          cache-to: type=inline
